######################################################################
# Automatically generated by qmake (3.0) sáb jan 23 13:19:29 2016
######################################################################

QT += core gui widgets

QMAKE_CXXFLAGS += -std=c++11 

TEMPLATE = app
TARGET = 00_Hello_World
INCLUDEPATH += .

# Input
SOURCES += main.cpp


DESTDIR = build-files
